### ISSUE TITLE
How can I use authentication with storage service?

### ISSUE THREAD

**Issue by chocstarfish** [strongloop/loopback-component-storage#10] opened 2014-04-10 14:24 UTC
I'd like to use authentication with the loopback storage service to make users can only upload to or delete files in their particular folders? I cannot find any document on that, so please give me some hints.

**Comment by kwiky** [comment] 2015-01-14 09:22
@raymondfeng looks like it doesn't work anymore with loopback 2.10.0.
Maybe because of this : https://github.com/strongloop/loopback/commit/16210e0f796089dc6a2a1e3d2a325ef9ef87243e

**Comment by seminice** [comment] 2015-07-07 07:22
@kwiky doesnt seem to work with loopback 2.18 
Any suggestions?

**Comment by antoniodimariano** [comment] 2015-11-11 15:48
@kwiky  I was wondering if you could share with us your example with 'download and upload property.
Did you write functions for both properties? 
Thank you

**Comment by richardpringle** [comment] 2016-01-14 18:15
@seminice, did you figure out a fix or a workaround?

**Comment by Morriz** [comment] 2016-02-19 11:29
It seems that $authenticated is not allowed in the storage context:
```
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW"
    },
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW",
      "property": "download"
    }
```
If I change ```$authenticated``` to ```$everyone``` 'download' starts to work.
Why is that?

**Comment by richardpringle** [comment] 2016-03-24 19:04
Works on LoopBack 2.27.0. I am closing this issue.

Please re-open the issue if your are still experiencing problems!

**Comment by MichaelKohler** [comment] 2016-04-08 13:43
> Works on LoopBack 2.27.0. I am closing this issue.

This is not true for me. I have the following versions:

    "loopback": "^2.27.0",
    "loopback-boot": "^2.18.0",
    "loopback-component-explorer": "^2.4.0",
    "loopback-component-storage": "^1.7.0",
    "loopback-connector-mongodb": "1.13.2",
    "loopback-datasource-juggler": "^2.46.0",

And I have this in my container.json:

"acls": [
        {
            "accessType": "*",
            "principalType": "ROLE",
            "principalId": "$everyone",
            "permission": "DENY"
        },
        {
            "accessType": "READ",
            "permission": "ALLOW",
            "principalType": "ROLE",
            "principalId": "$everyone"
        },
        {
            "accessType": "EXECUTE",
            "property": "upload",
            "principalType": "ROLE",
            "principalId": "admin",
            "permission": "ALLOW"
        }
    ]

Still, as long as the $everyone DENY is in there, I can't upload anything with the admin. @richardpringle  Could you please investigate again? Feel free to get back to me if you have any questions.

**Comment by richardpringle** [comment] 2016-04-08 15:38
@MichaelKohler, can you fork [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) and reproduce? Or even [loopback-example-storage](https://github.com/strongloop/loopback-example-storage).

Please make sure that you update `package.json`. 

Are you guys using the filesystem too? Let's see if we can get to the bottom of this!

**Comment by MichaelKohler** [comment] 2016-04-13 15:03
> can you fork loopback-sandbox and reproduce? Or even loopback-example-storage.

And of course it works. The problem was (embarrassingly) on our side since the Authorization header was missing.. Sorry about the fuzz and thanks for your help!

**Comment by richardpringle** [comment] 2016-04-13 17:58
Haha no worries, I'm just happy that it's working now!

**Closed by richardpringle** 2016-04-13 17:58 UTC
Labels: triage, waiting

**Comment by casamia918** [comment] 2016-04-30 00:29
I want to only the owner can delete or update their own files. Persist models related by User can do this in a simple way. For example, User can have many contacts and only the owner user can READ or WRITE their contacts.

```
[models/user.json]
"relations": {
    "contacts": {
      "type": "hasMany",
      "model": "contact",
      "foreignKey": "ownerId"
    },
    ....
}
"acls": [
  ....
    {
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW",
      "property": [
        "__create__contacts",
        "__findById__contacts",
        "__get__contacts",
        "__updateById__contacts",
        "__destroyById__contacts"
      ]
    }
  ],
...
```

Like this, I want to have has-many relation with user and file. But storage component backed model seems to different with other models. Can someone give guide to me?

**Comment by Morriz** [comment] 2016-04-30 08:20
Well, it's not a model actually, just grouped functionality, exposed over rest, which you can use parts of to hook up to your models.

So you create your own methods on your models that expose what you need and internally use the container's methods.

For example, create model AppUser, and create a POST method 'upload'. Now you can use ACL like you are used to.

**Comment by richardpringle** [comment] 2016-05-02 20:02
I agree that this is the best method ^

**Comment by Morriz** [comment] 2016-05-02 20:22
Wow, how did my last comment end up here? Too many threads, can't find where it should go anymore :p

**Comment by richardpringle** [comment] 2016-05-03 13:15
@Morriz, haha I didn't even look at the rest of the thread. I remember the issue you meant to comment on. If I come across it, I will create a link (at least this issue number will be easy to remember).

**Comment by fuzzball1980** [comment] 2016-06-01 20:12
Hi guys, same problem here with this ACL

```
{
  "name": "container",
  "plural": "containers",
  "base": "Model",
  "acls": [{
    "accessType": "*",
    "principalType": "ROLE",
    "principalId": "admin",
    "property": "*",
    "permission": "ALLOW"
  }, {
    "accessType": "EXECUTE",
    "property": "download",
    "permission": "DENY",
    "principalType": "ROLE",
    "principalId": "$everyone"
  }, {
    "accessType": "EXECUTE",
    "property": "upload",
    "principalType": "ROLE",
    "principalId": "$everyone",
    "permission": "DENY"
  }],
  "methods": []
}
```

"name": "loopback-component-storage", "version": "1.8.1"

"name": "loopback", "version": "2.28.0"

Any idea? i have tried EXECUTE in place of * for the admin but sil getting HTTP/401

Thank you!

**Comment by richardpringle** [comment] 2016-06-02 15:08
@fuzzball1980, can you fork [the loopback-sandbox](https://github.com/strongloop/loopback-sandbox), re-create the issue, post a link in here, and mention me please?

**Comment by fuzzball1980** [comment] 2016-06-02 19:50
@richardpringle my bad, for some reason I was not passing the accessToken!

It's working now!

Thank you!!

**Comment by richardpringle** [comment] 2016-06-03 23:07
Again, no worries, I'm just happy that it works!

**Comment by haydenkaizeta** [comment] 2016-06-27 19:50
How do you pass the access_token from the Android SDK when trying to access a container? Calling `.upload(File, Callback)` just returns "Unauthorized". Thanks

**Comment by fuzzball1980** [comment] 2016-06-29 16:45
add to the url the following parameter

URL + '?access_token=' + LoopBackAuth.accessTokenId;



Cesar.-

**Comment by coco-napky** [comment] 2017-09-13 05:07
I needed only authenticated users to be able to download files and for some reason **$authenticated** was not working.

My solution was to manually verify the access token with a before remote hook on the Download Remote Method.

```
Container.beforeRemote('download', (ctx, output, next) => {
    const AccessToken = Container.app.models.AccessToken;

    if(!ctx.req.query.access_token)
      return next({message: 'Authorization Required', statusCode: 401});

    AccessToken.resolve(ctx.req.query.access_token, (err, token) => {
      if(err)
        return next(err);

      if(!token)
        return next({message: 'Invalid Token', statusCode: 401});
      return next();
    });
  });
}
```

**Comment by bigktmbig** [comment] 2018-01-17 03:12
{
  "principalType": "ROLE",
  "principalId": "$everyone",
  "permission": "DENY"
},
{
  "accessType": "READ",
  "principalType": "ROLE",
  "principalId": "$everyone",
  "permission": "ALLOW",
  "property": "getContainer"
},
{
  "accessType": "READ",
  "principalType": "ROLE",
  "principalId": "$everyone",
  "permission": "ALLOW",
  "property": "getContainers"
},
{
  "accessType": "EXECUTE",
  "principalType": "ROLE",
  "principalId": "$everyone",
  "permission": "ALLOW",
  "property": "createContainer"
},
{
  "accessType": "EXECUTE",
  "principalType": "ROLE",
  "principalId": "$everyone",
  "permission": "ALLOW",
  "property": "upload"
}



all method:
Container.disableRemoteMethod('createContainer', true)
Container.disableRemoteMethod('getContainer', true)
Container.disableRemoteMethod('getContainers', true)
Container.disableRemoteMethod('destroyContainer', true)
Container.disableRemoteMethod('download', true)
Container.disableRemoteMethod('removeFile', true)
Container.disableRemoteMethod('getFiles', true)
Container.disableRemoteMethod('getFile', true)
Container.disableRemoteMethod('upload', true)
