### ISSUE TITLE
how to download file from a folder?

### ISSUE THREAD

**Issue by Ashish0019** [strongloop/loopback-component-storage#98] opened 2015-11-09 06:00 UTC
Hi,
Using this component I am able to upload file in a folder but how can i download it from a particular folder inside the bucket.
Please help

**Comment by loay** [comment] 2015-11-10 15:45
Is there a specific error that you are getting when you are trying to download?
Within the rep, there are 2 examples. When you upload a file, it shows in the list of files that are in the containers. You can either click on the file or right click to save. 
Please let me know if you are getting a specific error or a repo with the failing error. .

**Comment by loay** [comment] 2015-11-12 21:25
@Ashish0019 
Are you trying to get the files list to download from REST?
Did you try to look in explorer?
Assuming we are looking in "container1"
```
.../api/containers/container1/files
```

**Comment by Ashish0019** [comment] 2015-11-16 04:25
When i try to download file using from a folder inside of s3 bucket using via API explore I get 500 internal server error 
GET /Buckets/{container}/download/{folder}/{file}

**Comment by loay** [comment] 2015-11-16 15:06
@Ashish0019 Sorry I can't reproduce on my end. Is there a repo I can clone to test on my end?
If not, can you please create a repo and give me the link so I can fork it? Thanks.

**Comment by alexxgathp** [comment] 2016-01-09 00:29
One comment about this - With the local file storage I am able to download by having it as a link that the user clicks on- 

http://base_url/api/storage_name/container_name/download/filename

**Comment by richardpringle** [comment] 2016-03-14 11:47
Looks to me like this is solved, I am closing the issue for now, please re-open if the issue persists!

**Closed by richardpringle** 2016-03-14 11:47 UTC
Labels: triage, waiting

**Comment by casamia918** [comment] 2016-05-06 05:57
I have same problem too.
This issue is related with 
https://github.com/strongloop/loopback-component-storage/issues/31

I create storage connected to aws s3. As known, s3 bucket is equal to loopback container. 
But in the #31 issue, someone gives a solution to uplode file in a folder in a bucket using getFilename method. 
The upload result is [Bucket-name] /[folder-name] / [file-name] 

So, I successfully upload file. But when I tried to download that file, the result is always error.

For example, I have a sample file in a s3 bucket with the below structure
bucket : sampleBucket
folder : sampleFolder1
file : sampleFile1

But when I try to download that file, using this url
GET /api/containers/sampleBucket/download/sampleFolder/sampleFile1

The return message is this

{
  "error": {
    "name": "Error",
    "status": 404,
    "message": "Shared class \"Container\" has no method handling GET /sampleBucket/download/sampleFolder/sampleFile1",
    "statusCode": 404
  }
}
 

I tried using another url, which seperate the folder into header 
GET /api/containers/sampleBucket/download/sampleFile1
in header : folder = sampleFolder

Then, the response is "The specified key does not exist"

How to solve this?

**Comment by richardpringle** [comment] 2016-05-06 15:09
@casamia918, I am afraid that if we continue the discussion in here the scope of the issue will be lost. Could you please open a new issue with a descriptive title and mention me in a comment? You can copy over the comment above as well. Please use [code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) in your comments too.

As for the issue, if my understanding is correct, it's only with amazon right? If you change the exact same code to use your file system, will it work?

As I said, let's continue the discussion in a new issue. Please remember to mention me directly or I might not see it!

**Comment by MichaelMarner** [comment] 2016-08-08 04:15
The trick is to urlencode the `/

**Comment by BahodurSaidov** [comment] 2017-05-23 08:15
@MichaelMarner for throws error even if i urlencode
`http://localhost:3000/api/containerTests/moved/download/one%2Ftochka1.png`
container is moved and subfolder one -> moved/one/filename.png
`name	"Error"
status	500
message	"FileSystemProvider: Invalid name: one/tochka1.png"
stack	"Error: FileSystemProvider: Invalid name: one/tochka1.png
    at FileSystemProvider.download (/Users/programmer/codingNodeApps/docUploader/node_modules/loopback-component-storage/lib/providers/filesystem/index.js:228:7)
    at download (/Users/programmer/codingNodeApps/docUploader/node_modules/loopback-component-storage/lib/storage-handler.js:255:27)
    at Object.exports.download (/Users/programmer/codingNodeApps/docUploader/node_modules/loopback-component-storage/lib/storage-handler.js:242:12)
    at StorageService.download (/Users/programmer/codingNodeApps/docUploader/node_modules/loopback-component-storage/lib/storage-service.js:268:18)
    at SharedMethod.invoke (/Users/programmer/codingNodeApps/docUploader/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:263:25)
    at HttpContext.invoke (/Users/programmer/codingNodeApps/docUploader/node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:389:12)
    at phaseInvoke (/Users/programmer/codingNodeApps/docUploader/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:654:9)
    at runHandler (/Users/programmer/codingNodeApps/docUploader/node_modules/loopback/node_modules/loopback-phase/lib/phase.js:135:5)
    at iterate (/Users/programmer/codingNodeApps/docUploader/node_modules/loopback/node_modules/loopback-phase/node_modules/async/lib/async.js:146:13)
    at Object.async.eachSeries (/Users/programmer/codingNodeApps/docUploader/node_modules/loopback/node_modules/loopback-phase/node_modules/async/lib/async.js:162:9)
    at runHandlers (/Users/programmer/codingNodeApps/docUploader/node_modules/loopback/node_modules/loopback-phase/lib/phase.js:144:13)
    at iterate (/Users/programmer/codingNodeApps/docUploader/node_modules/loopback/node_modules/loopback-phase/node_modules/async/lib/async.js:146:13)
    at /Users/programmer/codingNodeApps/docUploader/node_modules/loopback/node_modules/loopback-phase/node_modules/async/lib/async.js:157:25
    at /Users/programmer/codingNodeApps/docUploader/node_modules/loopback/node_modules/loopback-phase/node_modules/async/lib/async.js:154:25
    at execStack (/Users/programmer/codingNodeApps/docUploader/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:493:7)
    at RemoteObjects.execHooks (/Users/programmer/codingNodeApps/docUploader/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:497:10)"`

any workarounds????

**Comment by BahodurSaidov** [comment] 2017-05-23 08:28
Why this thread is closed ?
 @richardpringle what is the final solution for this issue ????

**Comment by richardpringle** [comment] 2017-05-23 13:32
Hey @BahodurSaidov, I'm actually not working on this project (LoopBack) anymore. 

Buuuuuuut, I know that a file location string in s3 is `<folder-name>/<file-name>` where the folder name is actually just a prefix on the file location. s3 doesn't actually have the concept of folders within buckets, it's *only* a prefix on the location string.

The issue is then that `express` treats the `/` as a separator in the url. The `%2F` should fix the issue with s3. Although, I see that it hasn't.

You should probably try to download the file programmatically through the javascript API instead of the REST API to see where the problem is. If it persists, try opening a new issue. You should also make sure that you can download your file from s3 directly with the aws cli or through curl, or something of the like to make sure that you have managed to isolate the issue.

If you have already isolated the issue, please provide the details of how you did so as it will help the LoopBack developer locate the source quicker (and thus get the fix in quicker).

I would also suggest that you open up a new issue in the LoopBack core with all the details of the case as mentioned above. You're issue will probably get more attention that way. Mention me in the LoopBack core issue too and I'll see if I can help out in the discussion.

Good luck!

**Comment by sanjayradadiyadev** [comment] 2018-08-15 09:12
I create storage connected to aws s3. As known, s3 bucket is equal to loopback container.
But when i try to get file from a bucket using downloadStream/download method it will return  blank data. also getFile method working fine  and return file data

```
reader = ContainerFontFile.downloadStream(containerName, fileInfo.name, function(stream) {
          return console.log('--------------', stream);
          return next(null, null);
        });
        console.log(reader);
```
