### ISSUE TITLE
Using Amazon S3 and requesting a file Returns 500 to the client when file doesn't exist

### ISSUE THREAD

**Issue by jaime-franco** [strongloop/loopback-component-storage#126] opened 2016-05-06 14:24 UTC
When you use Amazon S3 and request a file that is not in the bucket the server returns 500, with a message : 

`
{
  "error": {
    "message": "The specified key does not exist.",
    "code": "NoSuchKey",
    "region": null,
    "time": "2016-05-05T23:06:05.754Z",
    "requestId": "638EDCE6C4A26F92",
    "extendedRequestId": "jQF3rslwLLatYfRPbm4pnJwuCDgUpE+tVcGccULi2m10LylNMuhowUOJlFlBCQDVpv8Vd5NDqdw=",
    "statusCode": 404,
    "retryable": false,
    "retryDelay": 12.993586948141456
  }
}
`

As you can see Amazon returns a 404 status, but the actual status that came back to the web browser is 500 Internal error server.

For reproduce the error is simple : 
1.Set up a S3 account
2.Create a container
3.Ask a file that doesn't exist in the container

**Comment by superkhau** [comment] 2016-05-06 19:12
@jaime-franco Thanks for the report, it'll take awhile to get to it since I don't have an S3 account to test on, but I'll try to get on it to reproduce.

**Comment by cadesalaberry** [comment] 2016-11-18 10:06
Should be fixed by #174

**Comment by superkhau** [comment] 2016-12-07 08:04
@cadesalaberry TY, closing as resolved by #174

**Closed by superkhau** 2016-12-07 08:04 UTC
Labels: triage
