### ISSUE TITLE
upload method doesn't wait for files to be written

### ISSUE THREAD

**Issue by HansHammel** [strongloop/loopback-component-storage#68] opened 2015-05-31 10:53 UTC
the upload method doesn't wait for files to be written. may be related to several other issues complaining about missing finished events. my hotfix is a setTimout-wrapper for now. very annoying.

**Comment by dhirenderbp** [comment] 2015-06-01 06:44
But your hotfix will not work for multiple upload. If you have some then pls share it.

**Comment by richardpringle** [comment] 2016-03-28 18:10
duplicate of #58

**Closed by richardpringle** 2016-03-28 18:10 UTC
