### ISSUE TITLE
there is not any finish event when uploads to s3 cloud

### ISSUE THREAD

**Issue by dhirenderbp** [strongloop/loopback-component-storage#67] opened 2015-05-27 14:08 UTC
It will return success before actually file uploads to s3 cloud. So there should be some event fire once the file actually uploaded to s3 cloud. Even in the example same process follow.

**Comment by richardpringle** [comment] 2016-03-28 18:09
Closing as this looks like a duplicate of #58

**Closed by richardpringle** 2016-03-28 18:09 UTC
