### ISSUE TITLE
Amazon S3 does't work

### ISSUE THREAD

**Issue by fostery** [strongloop/loopback-component-storage#37] opened 2015-01-09 21:01 UTC
Hi, I'm playing around the example 2.0 of this nice component and trying AWS S3. I put the right keys, but when I uploaded files from browser, I got this error: 

/Users/fostery/dev-playground/loopback/loopback-component-storage-master/example-2.0/node_modules/loopback/node_modules/continuation-local-storage/context.js:78
      throw exception;
            ^
TypeError: Cannot call method 'end' of undefined
    at ChunkedStream.<anonymous> (/Users/fostery/dev-playground/loopback/loopback-component-storage-master/example-2.0/node_modules/loopback-component-storage/node_modules/pkgcloud/lib/pkgcloud/amazon/storage/client/files.js:200:15)
    at ChunkedStream.emit (events.js:92:17)
    at ChunkedStream.end (/Users/fostery/dev-playground/loopback/loopback-component-storage-master/example-2.0/node_modules/loopback-component-storage/node_modules/pkgcloud/lib/pkgcloud/amazon/storage/utils.js:71:8)
    at Stream.<anonymous> (/Users/fostery/dev-playground/loopback/loopback-component-storage-master/example-2.0/node_modules/loopback-component-storage/lib/storage-handler.js:93:14)
    at Stream.emit (events.js:117:20)
    at MultipartParser.parser.onPartEnd (/Users/fostery/dev-playground/loopback/loopback-component-storage-master/example-2.0/node_modules/loopback-component-storage/node_modules/formidable/lib/incoming_form.js:382:14)
    at callback (/Users/fostery/dev-playground/loopback/loopback-component-storage-master/example-2.0/node_modules/loopback-component-storage/node_modules/formidable/lib/multipart_parser.js:102:31)
    at MultipartParser.write (/Users/fostery/dev-playground/loopback/loopback-component-storage-master/example-2.0/node_modules/loopback-component-storage/node_modules/formidable/lib/multipart_parser.js:267:15)
    at IncomingForm.write (/Users/fostery/dev-playground/loopback/loopback-component-storage-master/example-2.0/node_modules/loopback-component-storage/node_modules/formidable/lib/incoming_form.js:157:34)
    at IncomingMessage.<anonymous> (/Users/fostery/dev-playground/loopback/loopback-component-storage-master/example-2.0/node_modules/loopback-component-storage/node_modules/formidable/lib/incoming_form.js:123:12)

Any ideas? Do I miss anything? Thanks!

**Comment by raymondfeng** [comment] 2015-01-09 21:48
@superkhau Can you work with @fostery to reproduce the problem?

**Comment by fostery** [comment] 2015-01-12 15:03
any update please? Thanks!

**Comment by superkhau** [comment] 2015-01-12 17:59
@fostery Thanks for report!
@raymondfeng I will try to reproduce it.

**Comment by superkhau** [comment] 2016-02-03 02:16
@fostery Are you still running into issues?

@richardpringle Reassigning to you since you are the repo expert.

**Comment by richardpringle** [comment] 2016-03-14 11:41
Closing this issue. Please re-open if it is still relevant!

**Closed by richardpringle** 2016-03-14 11:41 UTC
Labels: triage, waiting

**Comment by developermhayden** [comment] 2017-02-24 20:59
Although I can get it to work with provider:'filesystem', I am unable to make loopback-component-storage work with provider: "amazon". I get 'access denied'. I can connect and upload files to 'Amazon s3' using npm module 's3'.
loopback-component-storage doesn't appear to have a place to specify 'Bucket'.

Here is error my config using loopback-component-storage:
"s3Container": {
      name: "[BUCKET NAME]",
      connector: "loopback-component-storage",
      provider: "amazon",
      key: "[key]",
      keyId: "[keyID]"
    }

Here is my working config using 's3' module:
var s3 = require('s3');
 
var client = s3.createClient({
  maxAsyncS3: 20,     // this is the default 
  s3RetryCount: 3,    // this is the default 
  s3RetryDelay: 1000, // this is the default 
  multipartUploadThreshold: 20971520, // this is the default (20 MB) 
  multipartUploadSize: 15728640, // this is the default (15 MB) 
  s3Options: {
    accessKeyId: "[key]",
    secretAccessKey: "[accessKey]",
    // any other options are passed to new AWS.S3() 
    // See: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#constructor-property 
  },
});

var params = {
  localFile: "/download.jpeg",
 
  s3Params: {
    Bucket: "[Bucket]",
    Key: "downloadFolder/download.jpeg",
    // other options supported by putObject, except Body and ContentLength. 
    // See: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property 
  },
};
var uploader = client.uploadFile(params);
uploader.on('error', function(err) {
  console.error("unable to upload:", err.stack);
});
uploader.on('progress', function() {
  console.log("progress", uploader.progressMd5Amount,
            uploader.progressAmount, uploader.progressTotal);
});
uploader.on('end', function() {
  console.log("done uploading");
});

**Comment by developermhayden** [comment] 2017-02-24 21:29
ok, I figured it out.
you have to include the bucket name in the url you posting to:
http://localhost:3000/api/v1/ImportContainers/AmazonS3BucketName/upload

This url showed me the way:
https://gist.github.com/reichert621/e987545fdbc2bc071d37
